### PR TITLE
Add GHC 9.4.4, 9.4.3, and 9.2.5

### LINKED ISSUE #129: Cannot install GHC 9.4.3 on windows
Installing GHC 9.4.3 on Windows fails. 9.4.2 works fine.

Here is the error message:

```
Run haskell/actions/setup@v2
[6](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:7)
Preparing to setup a Haskell environment
[7](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:8)
Preparing ghc environment
[8](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:10)
Installing ghc version 9.4.3
[9](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:11)
  Attempting to install ghc 9.4.3 using chocolatey
[10](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:12)
  ::stop-commands::***
[11](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:13)
  C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe choco install ghc --version 9.4.3 -m --no-progress -r
[12](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:14)
  Installing the same package with multiple versions is deprecated and will be removed in v2.0.0.
[13](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:15)
  Installing the following packages:
[14](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:16)
  ghc
[15](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:17)
  By installing, you accept licenses for the packages.
[16](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:18)
  
[17](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:19)
  ghc v9.4.3 [Approved]
[18](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:20)
  ghc package files install completed. Performing other installation steps.
[19](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:21)
  ERROR: Cannot bind argument to parameter 'Path' because it is null.
[20](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:22)
  Environment Vars (like PATH) have changed. Close/reopen your shell to
[21](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:23)
   see the changes (or in powershell/cmd.exe just type `refreshenv`).
[22](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:24)
  The install of ghc was NOT successful.
[23](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:25)
  Error while running 'C:\ProgramData\chocolatey\lib\ghc.9.4.3\tools\chocolateyInstall.ps1'.
[24](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:26)
   See log for details.
[25](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:27)
  
[26](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:28)
  Chocolatey installed 0/1 packages. 1 packages failed.
[27](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:29)
   See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
[28](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:30)
  
[29](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:31)
  Failures
[30](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:32)
   - ghc (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\ghc.9.4.3\tools\chocolateyInstall.ps1'.
[31](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:33)
   See log for details.
[32](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:34)
  C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe choco install ghc --version 9.4.3 -m --no-progress -r --pre
[33](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:35)
  Installing the same package with multiple versions is deprecated and will be removed in v2.0.0.
[34](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:36)
  Installing the following packages:
[35](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:37)
  ghc
[36](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:38)
  By installing, you accept licenses for the packages.
[37](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:39)
  
[38](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:40)
  ghc v9.4.3 [Approved]
[39](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:41)
  ghc package files install completed. Performing other installation steps.
[40](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:42)
  ERROR: Cannot bind argument to parameter 'Path' because it is null.
[41](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:43)
  The install of ghc was NOT successful.
[42](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:44)
  Error while running 'C:\ProgramData\chocolatey\lib\ghc.9.4.3\tools\chocolateyInstall.ps1'.
[43](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:45)
   See log for details.
[44](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:46)
  
[45](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:47)
  Chocolatey installed 0/1 packages. 1 packages failed.
[46](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:48)
   See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
[47](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:49)
  
[48](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:50)
  Failures
[49](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:51)
   - ghc (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\ghc.9.4.3\tools\chocolateyInstall.ps1'.
[50](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:52)
   See log for details.
[51](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:53)
  ::***::
[52](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:55)
Error: All install methods for ghc 9.4.3 failed
```

### PR DESCRIPTION
**Pull request by andreasabel**
This adds GHC versions 9.4.4 and 9.4.3 and 9.2.5 (the latter two were blocked by failure on Windows, #129).

Fixes #129:
- separate out choco revision mechanism (e.g. `9.4.3 -> 9.4.3.1`) from `resolved()` into new `releaseRevision()`
- this enables to find `ghc.exe`  correctly under `C:\tools\9.4.3` rather than the attempted `C:\tools\9.4.3.1`

Further:
- secure the problematic versions (7.10.3, 9.2.5, 9.4.3) by CI
- verbose chocolatey output in debug mode

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
Thank you for the fix. Can you also cut a new release for this please?

**Comment by andreasabel** [comment]
I released this as `v2.1.0`: https://github.com/haskell/actions/compare/v2.0.5...v2.1.0

**Comment by mihaimaruseac** [comment]
My bad, I didn't see it in https://github.com/haskell/actions/releases but it shows in https://github.com/haskell/actions/tags

I need to get into the habit of checking the tags too.

**Comment by andreasabel** [comment]
@mihaimaruseac : Manually making a "release" from a tag gets laborious in the _release early, release often_ style.
Maybe we should delete the two existing "releases" so that there are only the tags?  What do you think?

The first release might have some useful description:
> haskell/actions/setup is the continuation of the actions/setup-haskell project. Updates and fixes will be able to be merged in more rapidly.

(The second statement was maybe a new-year resolution which quickly fell apart. :-D)

**Comment by mihaimaruseac** [comment]
GitHub promotes the releases on the homepage of the repo, the tags not so much.

I'm thinking of adding a github action to create the release page automatically when you push the tag. Let me try to attempt this by the end of this week? :)

**Comment by andreasabel** [comment]
Sounds good.  Here is some prior art:
- https://github.com/BNFC/bnfc/blob/0c89d84c922df71b3704a149cc1e7ae758eccd58/.github/workflows/stack.yml#L134-L143
- https://github.com/agda/fix-whitespace/blob/4a2a71e7faa47ec80f9ebf8284b8554f28842dd1/.github/workflows/stack.yml#L25-L46

I have done this when I wanted to create binaries for the release with GHA.  
What would go into the release here?
- tag message as release message
- auto-changelog
- ...?

Happy hacking!

**Comment by mihaimaruseac** [comment]
Awesome. I was thinking for a start to start with just creating the release page with the release message. Then we can add as needed, changelog is really good.

I'll take a look to see what is in the repo and could go there.

**Comment by mihaimaruseac** [comment]
Created https://github.com/haskell/actions/pull/164 for the automatic creation of releases

**Pull request merged**
