### PR TITLE
Add GHC 9.4.2 and Stack 2.9.1

### PR DESCRIPTION
**Pull request by andreasabel**
Add GHC 9.4.2 and Stack 2.9.1.

### CODE REVIEW

**Comment by andreasabel** [comment]
@hazelweakly CI passes; I'd be grateful if this PR gets released quickly (in case it also works fine in reality).  The reason is that we have some [mysterious CI freezes](https://github.com/agda/agda/actions/runs/3153779362/jobs/5130713102) with Stack 2.7.5 on the latest Windows virtual environment, and I would like to test whether Stack 2.9.1 resolves this.

**Comment by yutotakano** [comment]
Eager for this to go in, I need the `stack ls tools` command in 2.9.1 to get the msys version used in my Windows CI.

**Comment by andreasabel** [comment]
I realized that `haskell/actions/setup` does allow e.g. `stack-2.9.1` if the version is specified in full, like `2.9.1`.  However, `2.9` cannot be resolved (without this PR) and also `latest` is outdated.  (Same for `ghc`.)

Ping @hazelweakly .

**Comment by andreasabel** [comment]
@hazelweakly I'd say this PR is safe to merge.  What do you think?

**Comment by andreasabel** [comment]
Ping @hazelweakly.

**Comment by hazelweakly** [comment]
I'd like to apologize for the late delay; it's been hard for me to have the energy to do OSS lately, but I've been able to finally pick it back up.

I also went through the repository permissions and realized I had somehow forgotten for nearly 2 years to add any of the haskell org groups... sigh. Not sure how this never came up, but I added relevant ones and also gave you commit bit because this isn't the first time I've kept you waiting for an unreasonable length of time on simple patches 😅

**Comment by andreasabel** [comment]
> I'd like to apologize for the late delay; it's been hard for me to have the energy to do OSS lately, but I've been able to finally pick it back up.

Apology accepted, happens to all of us, great that you are back!

> I also went through the repository permissions and realized I had somehow forgotten for nearly 2 years to add any of the haskell org groups... sigh. Not sure how this never came up, but I added relevant ones and also gave you commit bit because this isn't the first time I've kept you waiting for an unreasonable length of time on simple patches 😅

Thanks for enabling me, which demands responsibility to me.  So far, I could rely on you to assess the correctness of my patches.
Ideally, CI would verify that added GHC default versions will work.  E.g. if I added GHC 9.4.3 so that `latest` and `9.4` resolved to `9.4.3`, I would like to test this setup (on the relevant github virtual environments).  
But I guess this discussion should happen here:
- https://github.com/haskell/actions/issues/116

**Pull request merged**
