### PR TITLE
Add a problem matcher for GHC errors

### PR DESCRIPTION
**Pull request by bubba**
Allows for errors and warnings to be reported as annotations:

image

One limitation is that there doesn't seem to be support for matching a message field with multiple lines, so this just reports the first line of the error message

### CODE REVIEW

**Comment by jared-w** [comment]
Thanks for this! I've been wanting matcher support for a while.

Couple of quick comments I noticed:

1. It looks like the (somewhat obscurely located) [matcher docs](https://github.com/actions/toolkit/blob/master/docs/problem-matchers.md#multiline-matching) have a section on how to enable multiline-matching. That would be really cool to have, I think :) although I'm not sure how readable that'll be with massive type errors...
1. I expected the matcher.json file to be in the src directory somewhere, but upon looking at how all of the other libraries do this, it seems they all actually place the matcher.json file either in the `.github` folder or just the root folder of the repository.

   Regardless, placing it manually in the dist folder is not going to be ideal; dist (and lib) should be fully generated.

   For this current repository structure, I think it makes the most sense to place it in root (so `./setup/matcher.json`) and then refer to it in the source code with `path.join(__dirname, '..', 'matcher.json')`.  What do you think?

**Comment by bubba** [comment]
@jared-w re: the directory, sounds good

As for the multiline matching, I tried it out but it creates a new error for each line of the warning. So if there's one actual GHC error then 8 errors end up getting reported on GitHub. The actual message field cannot be matched upon multiple lines unfortunately

**Comment by jared-w** [comment]
Ah, you're right on the multiline matching, that's a bummer. I discovered a workaround that you an urlencode the newlines when outputting annotations, but this requires a custom output format for testsuites and compiler error messages that does the transformation, which is not something we can transparently/magically enable from this action. So, single line mode will suffice for now.

(There *might* be some way to abuse the `-ddump-json` GHC flag and set that in the environment somehow, but changing compiler flags on people implicitly is *really* something to think through carefully before even attempting. Gonna punt on that, personally)

**Comment by jared-w** [comment]
Thanks for the PR!

**Comment by Bodigrim** [comment]
This is an extremely nice feature, but could it be configured or at least disabled by user? 
In `bytestring` we support all GHCs back to 7.0, and it is expected that builds with old GHCs can produce warnings. Moreover, seeing a ton of repetitive warnings (one per build configuration) makes reviews quite unreadable: https://github.com/haskell/bytestring/pull/356/files#diff-26fda7ac4ab70e7f117dd9fa41349d429f2a1a0462893401dc4470e80694a3eb

**Comment by jared-w** [comment]
[xkcd](https://xkcd.com/1172/) strikes again, it seems. Unfortunately I don't have the ability to control how frequently warnings show up and there's no way for it to be intelligent enough to know that `cabal haddock` and `cabal test` will surface the same warnings twice. What a mess. GitHub should definitely reevaluate whether or not showing warnings for files that haven't changed makes sense (I don't think it does)

But yes, I think it makes sense to hide this behind a flag and make it opt out. The real solution to make this more robust is eventually going to be to implement a flag in cabal (or some environment variable awareness) that will have it natively output this type of information. Then we can remove the simplistic regex functionality from here.

**Comment by Bodigrim** [comment]
:) 

Yes, just a flag to opt-out would be fine. I have 4 builds for the same GHC version (but different OS), and displaying each warning repeated at least eight times is really annoying.

Thanks for all your hard work on this action!

**Pull request merged**
