### PR TITLE
Update dependencies for `hlint-setup` and `hlint-run`

### LINKED ISSUE #123: Update actions/core for set-output/state deprecation
Seeing these warnings when using `setup-hlint`, the other actions may be affected too:

```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

As visible the linked documentation, `set-output` (and `save-state`) are considered dangerous and have been replaced with environment files. If I understand correctly, you just need to update to `actions/core@1.10.0`.

It looks like you use Dependabot to keep your actions up to date; for what it's worth, you could extend that to manage these dependencies too.

### LINKED ISSUE #129: Cannot install GHC 9.4.3 on windows
Installing GHC 9.4.3 on Windows fails. 9.4.2 works fine.

Here is the error message:

```
Run haskell/actions/setup@v2
[6](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:7)
Preparing to setup a Haskell environment
[7](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:8)
Preparing ghc environment
[8](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:10)
Installing ghc version 9.4.3
[9](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:11)
  Attempting to install ghc 9.4.3 using chocolatey
[10](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:12)
  ::stop-commands::***
[11](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:13)
  C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe choco install ghc --version 9.4.3 -m --no-progress -r
[12](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:14)
  Installing the same package with multiple versions is deprecated and will be removed in v2.0.0.
[13](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:15)
  Installing the following packages:
[14](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:16)
  ghc
[15](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:17)
  By installing, you accept licenses for the packages.
[16](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:18)
  
[17](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:19)
  ghc v9.4.3 [Approved]
[18](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:20)
  ghc package files install completed. Performing other installation steps.
[19](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:21)
  ERROR: Cannot bind argument to parameter 'Path' because it is null.
[20](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:22)
  Environment Vars (like PATH) have changed. Close/reopen your shell to
[21](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:23)
   see the changes (or in powershell/cmd.exe just type `refreshenv`).
[22](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:24)
  The install of ghc was NOT successful.
[23](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:25)
  Error while running 'C:\ProgramData\chocolatey\lib\ghc.9.4.3\tools\chocolateyInstall.ps1'.
[24](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:26)
   See log for details.
[25](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:27)
  
[26](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:28)
  Chocolatey installed 0/1 packages. 1 packages failed.
[27](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:29)
   See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
[28](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:30)
  
[29](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:31)
  Failures
[30](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:32)
   - ghc (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\ghc.9.4.3\tools\chocolateyInstall.ps1'.
[31](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:33)
   See log for details.
[32](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:34)
  C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe choco install ghc --version 9.4.3 -m --no-progress -r --pre
[33](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:35)
  Installing the same package with multiple versions is deprecated and will be removed in v2.0.0.
[34](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:36)
  Installing the following packages:
[35](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:37)
  ghc
[36](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:38)
  By installing, you accept licenses for the packages.
[37](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:39)
  
[38](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:40)
  ghc v9.4.3 [Approved]
[39](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:41)
  ghc package files install completed. Performing other installation steps.
[40](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:42)
  ERROR: Cannot bind argument to parameter 'Path' because it is null.
[41](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:43)
  The install of ghc was NOT successful.
[42](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:44)
  Error while running 'C:\ProgramData\chocolatey\lib\ghc.9.4.3\tools\chocolateyInstall.ps1'.
[43](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:45)
   See log for details.
[44](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:46)
  
[45](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:47)
  Chocolatey installed 0/1 packages. 1 packages failed.
[46](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:48)
   See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
[47](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:49)
  
[48](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:50)
  Failures
[49](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:51)
   - ghc (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\ghc.9.4.3\tools\chocolateyInstall.ps1'.
[50](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:52)
   See log for details.
[51](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:53)
  ::***::
[52](https://github.com/gren-lang/compiler/actions/runs/3509357091/jobs/5878401466#step:4:55)
Error: All install methods for ghc 9.4.3 failed
```

### LINKED ISSUE #149: Remove set-output from hlint action
> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

The link above has a hard date for removing set-output.

> Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error.

### PR DESCRIPTION
**Pull request by pavelzw**
Closes #149 
Closes #123

### CODE REVIEW

**Comment by pavelzw** [comment]
Is `yarn all && yarn package` the correct way of building the `hlint-setup` and `hlint-run` actions?

**Comment by andreasabel** [comment]
> Is `yarn all && yarn package` the correct way for building the `hlint-setup` and `hlint-run` actions?

I don't know, I am not a JS programmer.  Also, I cannot find documentation on either of the commands you list here.

Anyway, did you test your patches?  I think you can do this by referring to the last commit of this PR, like:
```
- uses: haskell/hlint-setup@f43e41e8b44ed9c91394dae3ec0ba660528ddb08
```

**Comment by andreasabel** [comment]
Let's try it out!  Releasing this as `v2.2.0`.

**Comment by pavelzw** [comment]
> Anyway, did you test your patches?

The [CI inside this repository](https://github.com/haskell/actions/blob/6d103f80e473b25c79b2f5e78641d3abff710c96/.github/workflows/hlint-run.yml#L33-L40) already did :)

**Comment by andreasabel** [comment]
> The [CI inside this repository](https://github.com/haskell/actions/blob/6d103f80e473b25c79b2f5e78641d3abff710c96/.github/workflows/hlint-run.yml#L33-L40) already did :)

Ok, let's hope this is sufficient.  Thanks again for the contribution!

**Pull request merged**
