### PR TITLE
use ghcup on windows (clone of #192)

### LINKED ISSUE #70: Consider ghcup for windows
Right now, when I define

```yml
jobs:
  build-cabal:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        ghc: ['8.10.7', '9.0.1']
        cabal: ['3.4.0.0']
```

This will fail on windows only, because `8.10.7` isn't in choco yet. It's quite confusing, because different installers with different release schedules are used under the hood.

I merged https://gitlab.haskell.org/haskell/ghcup-hs/-/merge_requests/159 which would allow the installation procedure on windows to be:

```ps
curl.exe -O https://www.haskell.org/ghcup/sh/bootstrap-haskell.ps1
.\bootstrap-haskell.ps1 -InstallDir 'C:\' -InBash -Minimal
```

Leaving you with an msys2 installation (in `C:\ghcup\msys64`) and the ghcup binary (in `C:\ghcup\bin`), nothing more.

Installations of msys2 packages would be carried out via:

```ps
C:\ghcup\msys64\usr\bin\bash.exe -lc 'pacman --noconfirm -S package'
```

### LINKED ISSUE #97: Make ghc installation consistent across all os's (use ghcup as fallback for windows)
* Somewhat follow up of #70
* Afaik linux is using apt-get as the first method to install ghc and fallback to ghcup. However, as hvr/ppa is not updated anymore it is using ghcup for ghc >= 8.10
* Windows only uses chocolatey without fallback so sometimes you can install a new ghc version in linux cause it is in ghcup but no in windows cause it still was not uploaded (see https://github.com/haskell/actions/issues/70#issuecomment-1063889459)
* Otoh sometimes (more frequently than we want) the ghc release is broken in windows. The choco package maitainer try to fix the release downstream so use it to get a working ghc version would be good.
* [Quoting @jared-w](https://github.com/haskell/actions/issues/70#issuecomment-910452680) in the mentioned issue:

 > I think the windows images from GitHub still use chocolatey under the hood, so I would still default to that (for fastest setup time in the cloud), but I'm looking forward to being able to fall back to ghcup on Windows and possibly even switch to using it first if the action images start using ghcup for windows too.

### LINKED ISSUE #112: Option to use ghcup on Windows
The title tells it all.

### LINKED ISSUE #191: `ghcup` not found on `windows-2022` version 20230214.1
https://github.com/haskell/primitive/actions/runs/4202068611/jobs/7289771094#step:1:9
> Runner Image
>   Image: windows-2022
>   Version: 20230214.1

https://github.com/haskell/primitive/actions/runs/4202068611/jobs/7289771094#step:3:13
> Adding ghcup release channel: https://raw.githubusercontent.com/haskell/ghcup-metadata/master/ghcup-prereleases-0.0.7.yaml
> Error: Unable to locate executable file: C:\hostedtoolcache\windows\ghcup\0.1.19.0\x64\ghcup. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.

### PR DESCRIPTION
**Pull request by andreasabel**
Rebased clone of #192 to run latest CI.
- #192

Please also consider the discussion at #192.

TODO (correctness):
- [x] Fix unintended breakage of `apt` install method.
- [x] Write cabal `config` so that symlinking is off on Windows by default.
   * https://github.com/haskell/ghcup-hs/issues/808
- [ ] Exhaustively test different versions of cabal/ghc in CI for launch of the ghcup/Windows install method.
- [ ] Blocker: https://github.com/haskell/ghcup-hs/issues/823

TODO (features):
- [ ] Bring back `choco` install method (by option and/or as fallback).  E.g. we could have an input `setup-method` which is a list of install methods that are tried in order (if available for that platform).  The default could be for now `setup-method: [ghcup, choco, apt]`, but one could opt out of fallback by e.g. just `setup-method: [ghcup]`.
  (Bikeshedding: `method`, `install-method`.)

Closes #70. Closes #97. Closes #112. Closes #191.
- #70 
- #97
- #112
- #191

### CODE REVIEW

**Comment by andreasabel** [comment]
Atm, this PR also seems to destroy the `apt` installation method (fallback on linux): https://github.com/haskell/actions/actions/runs/4410084290/jobs/7727167607#step:3:146
We might give up `apt` soon when `ubuntu-18.04` is removed at the end of the month:
- https://github.com/actions/runner-images/issues/6002

**Comment by andreasabel** [comment]
Windows CI with cabal 3.0 and 3.2 fails with error `cabal: symlinking feature not available on Windows`.  Not sure if this should be fixed in ghcup or whether the setup action needs to work around this problem.
- https://github.com/haskell/ghcup-hs/issues/808

**Comment by ulysses4ever** [comment]
The symlinking issue has a long history on cabal bugtracker (e.g. https://github.com/haskell/cabal/issues/5748). Chocolatey fixes it here: https://github.com/Mistuke/CabalChoco/blob/656b693745acd0f91d2ef06b3ecfb2ab9051d65d/3.2.0.0/cabal/tools/chocolateyInstall.ps1#L286 If ghcup doesn't include the same fix, then either the action has to include it (it's simply a matter of `cabal user-config update -a "install-method: copy"`) or just stop trying to fix this issue. I'm not sure how useful it is to support/patch earlier `cabal-install`s, so the second option doesn't sound too bad to me.

**Comment by ulysses4ever** [comment]
Good to see the progress here, thank you.

More generally, I wanted to share a doubt I was contemplating over the weekend after I learned a bit about the CabalChoco/GhcChoco repos. It looks like supporting Windows required a lot of downstream patching. The fact that CI caught the symlinking issue may be a sheer luck, and more issues may go unnoticed until the switch from Chocolatey to ghcup goes public. So, maybe the change in its current form is a bit radical. Maybe something more cautious like switching to ghcup only when newer cabals are requested (e.g. starting from 3.10 or something). It may also be easier to convince the ghcup maintainer to patch new releases when/if such a need pops up than it is for old releases.

This is just some rough thought, and it's up to the maintainers of respective facilities to decide, of course.

**Comment by andreasabel** [comment]
I brought back Choco as default, for the sake of backwards compatibility.  
CI passes, but I have some regression in the wild that _could_ be caused by switching to ghcup:
- https://github.com/commercialhaskell/stack/issues/6111

**Pull request merged**
