### PR TITLE
Added test for checking stack-root output

### PR DESCRIPTION
**Pull request by sgadkar2**

### CODE REVIEW

**Comment by andreasabel** [comment]
Thanks!
This had two problems:
- `steps.setup` was undefined because the setup step was not named in this job.
   I recommend using `actionlint` to find such problems before shipping.
- `stack` installed a GHC.  This can be avoided (I hope) by passing `--system-ghc`.  We might have to take this into account for #230.

I pushed a commit hopefully fixing this.

**Comment by andreasabel** [comment]
On windows, we still have a problem with backslashes: https://github.com/haskell/actions/actions/runs/4623203883/jobs/8176768081#step:5:96
```
Returned stack-root: C:sr
Expected stack-root: C:\sr
```

**Comment by andreasabel** [comment]
Ok, works now!

**Comment by sgadkar2** [comment]
Great. Thanks for your help.

**Comment by andreasabel** [comment]
Pushed as  87b3442d9877a4ab61f04a4e3d0da2e14be5d51e  to `main`.

**Comment by andreasabel** [comment]
@sgadkar2 : It would be nice if the test was extended to check that `${STACK_ROOT}`, if set, is also the same as `outputs.stack-root` and `$(stack path --stack-root)`.

**Pull request closed without merging**
